/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myTextField;

import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author Reakkidingg_
 */
public class NewJFrame extends javax.swing.JFrame {

    NumberField numberFieldHandle = new NumberField();
    FloatingField floatingFieldHandle = new FloatingField();
    LetterField letterFieldHandle = new LetterField();
    StringField stringFieldHandle = new StringField();

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        // Disable copy and paste for all text fields
        disableCopyAndPaste(NumberFieldInput);
        disableCopyAndPaste(Floating);
        disableCopyAndPaste(LetterFieldInput);
        disableCopyAndPaste(StringFieldInput);
    }
    private void disableCopyAndPaste(JTextField textField) {
        InputMap inputMap = textField.getInputMap();
        ActionMap actionMap = textField.getActionMap();

        KeyStroke[] emptyKeyStrokes = new KeyStroke[0];

        // Disable paste
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        actionMap.put("null", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Do nothing
            }
        });

        // Disable copy
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_C, Event.CTRL_MASK), "null");
        actionMap.put("null", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Do nothing
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumberFieldInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Floating = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LetterFieldInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        StringFieldInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NumberFieldInput.setColumns(5);
        NumberFieldInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NumberFieldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberFieldInputActionPerformed(evt);
            }
        });
        NumberFieldInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumberFieldInputKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("NumberField:");

        Floating.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Floating.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FloatingKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("FloatingField:");

        LetterFieldInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LetterFieldInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LetterFieldInputKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("LetterField:");

        StringFieldInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StringFieldInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StringFieldInputKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("StringField:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("WELCOME TO JAVA FRAME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(44, 44, 44)
                                .addComponent(StringFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(44, 44, 44)
                                .addComponent(LetterFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44)
                                .addComponent(Floating, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)
                                .addComponent(NumberFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel5)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Floating, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LetterFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StringFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(78, 78, 78))
        );

        setSize(new java.awt.Dimension(729, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FloatingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FloatingKeyTyped
        floatingFieldHandle.handleKeyTyped(evt);
    }//GEN-LAST:event_FloatingKeyTyped

    private void LetterFieldInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LetterFieldInputKeyTyped
        // TODO add your handling code here:
        letterFieldHandle.handleKeyTyped(evt);
    }//GEN-LAST:event_LetterFieldInputKeyTyped

    private void StringFieldInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StringFieldInputKeyTyped
        // TODO add your handling code here:
        stringFieldHandle.handleKeyTyped(evt);
    }//GEN-LAST:event_StringFieldInputKeyTyped

    private void NumberFieldInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumberFieldInputKeyTyped
        numberFieldHandle.handleKeyTyped(evt);
    }//GEN-LAST:event_NumberFieldInputKeyTyped

    private void NumberFieldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberFieldInputActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_NumberFieldInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Floating;
    private javax.swing.JTextField LetterFieldInput;
    private javax.swing.JTextField NumberFieldInput;
    private javax.swing.JTextField StringFieldInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
